# -*- coding: utf-8 -*-
# Name::        automatic.gemspec
# Author:       id774 (More info: http://id774.net)
# Source Code:: https://github.com/id774/automaticruby
# License::     The GPL version 3, or LGPL version 3 (Dual License).
# Contact::     idnanashi@gmail.com
# Created::     Mar  7, 2012
# Updated::     Aug 14, 2026
# Copyright::   Copyright (c) 2012-2026 Automatic Ruby Developers.
#
# This file is maintained by hand. It was generated by Jeweler until v14.12.2;
# the generator is no longer maintained and the file is now source. See
# doc/POLICY.md section 9.4.

Gem::Specification.new do |spec|
  spec.name        = 'automatic'
  spec.version     = File.read(File.expand_path('VERSION', __dir__)).strip
  spec.authors     = ['id774']
  spec.email       = ['idnanashi@gmail.com']

  spec.summary     = 'Automatic Ruby'
  spec.description = <<~DESC
    A Ruby framework for general-purpose automatic processing. A job is
    described in a YAML file called a Recipe, which names plugins in order;
    each plugin receives the previous one's output and returns the next one's
    input. Subscribing, filtering, storing and publishing are all plugins, and
    a plugin is found by name on a search path rather than registered.
  DESC

  spec.homepage = 'https://github.com/id774/automaticruby'
  spec.licenses = ['GPL-3.0-only', 'LGPL-3.0-only']

  spec.metadata = {
    'source_code_uri'   => spec.homepage,
    'bug_tracker_uri'   => "#{spec.homepage}/issues",
    'changelog_uri'     => "#{spec.homepage}/blob/master/doc/VERSIONS",
    'documentation_uri' => "#{spec.homepage}/blob/master/README.md",
    'rubygems_mfa_required' => 'true'
  }

  # Ruby 3.3 is the floor: the oldest maintained release the dependencies are
  # resolved and tested against. The code is written for Ruby 3.3 through 4.0.
  #
  # A lower bound only, and deliberately so. An upper bound would refuse a Ruby
  # this code has every reason to work on, on the day it is released, and the
  # only way to lift it would be a new release of this gem. What CI validates
  # is a separate and narrower statement; see doc/REQUIREMENTS.md section 20.
  spec.required_ruby_version = '>= 3.3.0'

  # Shipped files. Derived from what Git sees, so that the list cannot drift
  # from the repository; the Dir fallback is for building outside a checkout.
  #
  # --others --exclude-standard includes a file that has been created but not
  # yet added, while still honouring .gitignore. Listing only --cached silently
  # omits a new file from the built gem, which is a trap worth avoiding.
  tracked =
    begin
      Dir.chdir(__dir__) {
        `git ls-files -z --cached --others --exclude-standard`.split("\x0")
      }
    rescue StandardError
      []
    end

  tracked = Dir.chdir(__dir__) {
    Dir.glob(
      [
        'bin/*', 'lib/**/*.rb', 'plugins/**/*.rb', 'config/*.yml',
        'assets/**/*', 'doc/*', 'README.md', 'VERSION', 'automatic.gemspec'
      ]
    )
  } if tracked.empty?

  # Gemfile and Rakefile are development files and are deliberately not
  # shipped: lib/automatic/environment.rb treats the presence of a Gemfile
  # beside lib/ as "this is a source checkout", so shipping one would make an
  # installed gem impose its own bundle on the program requiring it.
  excluded = %w[.gitignore .github Gemfile Rakefile script spec test vendor]
  spec.files = tracked.reject { |path|
    path.end_with?('.gem') ||
      excluded.any? { |prefix| path == prefix || path.start_with?("#{prefix}/") }
  }.select { |path| File.file?(File.join(__dir__, path)) }

  spec.bindir             = 'bin'
  spec.executables        = ['automatic']
  spec.require_paths      = ['lib']
  spec.extra_rdoc_files   = ['README.md', 'doc/LICENSE.md']

  # Runtime dependencies: what the framework in lib/ requires, and nothing
  # else. Requiring `automatic`, loading a Recipe, loading a plugin, running a
  # pipeline and the CLI's own work are what these four are for.
  #
  # A gem needed by a plugin is NOT declared here, however useful that plugin
  # is. It is required inside the plugin's own file and installed by the
  # operator who uses the plugin: `gem install automatic` therefore installs no
  # HTML parser, no database and no service client. The optional gems, which
  # plugin needs which, and how to install them are in the Gemfile's optional
  # groups, doc/DEPLOYMENT.md and doc/POLICY.md section 9.1.
  #
  # rexml and rss left the standard library and became gems over the 3.x
  # series, and nkf followed after 3.3. Each gem listed here is listed because
  # a file in lib/ requires it, and a library's move out of the standard
  # library is not by itself a reason to declare it: nkf is a plugin's
  # dependency and is in the Gemfile's optional groups instead.
  spec.add_dependency 'activesupport', '>= 7.1', '< 9.0'   # plugin loader, XML subscription
  spec.add_dependency 'hashie',        '>= 4.0', '< 6.0'   # Recipe
  spec.add_dependency 'rexml',         '>= 3.2', '< 4.0'   # OPML parser
  spec.add_dependency 'rss',           '>= 0.3', '< 1.0'   # the pipeline value

  spec.add_development_dependency 'rake',                      '~> 13.0'
  spec.add_development_dependency 'rspec',                     '~> 3.13'
  spec.add_development_dependency 'rspec-collection_matchers', '~> 1.2'
  spec.add_development_dependency 'rspec-its',                 '>= 1.3', '< 3.0'
  spec.add_development_dependency 'simplecov',                 '>= 0.22', '< 2.0'
end
